version: '3'
services:
  web:
    build: ./app
    restart: always
    environment:
      - FLASK_DEBUG=1
    command: ["flask", "run", "--host=0.0.0.0"]
    volumes:
      - .:/webapp
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    restart: always
    build:
      ./postgresql
    volumes:
      - ./postgres-data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"