version: '3'
services:
  web:
    build: .
    restart: always
    environment:
      - FLASK_DEBUG=1
      - ENV=test
    command: ["flask", "run", "--host=0.0.0.0"]
    volumes:
      - .:/home/match-post-service/
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    restart: always
    build:
      ./postgresql
    volumes:
      - ./postgres-data/postgres:/var/lib/postgresql/data
    ports:
      - "5433:5432"