"""added url column to preferences table to autogenerate url

Revision ID: 125dfd2ea6d5
Revises: b391b04254ce
Create Date: 2018-02-10 18:37:16.040601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '125dfd2ea6d5'
down_revision = 'b391b04254ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('preferences', sa.Column('url', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('preferences', 'url')
    # ### end Alembic commands ###
