"""added candidate model

Revision ID: 172d158513b1
Revises: 9a22f7b21ac1
Create Date: 2018-01-29 14:39:17.757913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '172d158513b1'
down_revision = '9a22f7b21ac1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organisation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=1024), nullable=True),
    sa.Column('type', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organisation_name'), 'organisation', ['name'], unique=True)
    op.create_table('candidate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('staff_number', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('staff_number')
    )
    op.add_column('activity_manager', sa.Column('organisation', sa.Integer(), nullable=True))
    op.drop_constraint('activity_manager_department_fkey', 'activity_manager', type_='foreignkey')
    op.create_foreign_key(None, 'activity_manager', 'organisation', ['organisation'], ['id'])
    op.drop_column('activity_manager', 'department')
    op.add_column('department', sa.Column('parent_dept', sa.String(length=256), nullable=True))
    op.drop_index('ix_department_name', table_name='department')
    op.create_foreign_key(None, 'department', 'organisation', ['id'], ['id'])
    op.drop_column('department', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('department', sa.Column('name', sa.VARCHAR(length=1024), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'department', type_='foreignkey')
    op.create_index('ix_department_name', 'department', ['name'], unique=True)
    op.drop_column('department', 'parent_dept')
    op.add_column('activity_manager', sa.Column('department', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'activity_manager', type_='foreignkey')
    op.create_foreign_key('activity_manager_department_fkey', 'activity_manager', 'department', ['department'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('activity_manager', 'organisation')
    op.drop_table('candidate')
    op.drop_index(op.f('ix_organisation_name'), table_name='organisation')
    op.drop_table('organisation')
    # ### end Alembic commands ###
