"""added tablename for cls

Revision ID: 45f3eeaea47f
Revises: b8c18b09d237
Create Date: 2018-02-08 10:54:31.596746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45f3eeaea47f'
down_revision = 'b8c18b09d237'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cohort_leaders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('cohort_leader')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cohort_leader',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id'], ['users.id'], name='cohort_leader_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='cohort_leader_pkey')
    )
    op.drop_table('cohort_leaders')
    # ### end Alembic commands ###
