"""added specialism attribute to candidate and specialisms model

Revision ID: 4a357332e312
Revises: 783f7bedee53
Create Date: 2018-02-08 00:31:53.660256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a357332e312'
down_revision = '783f7bedee53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('specialisms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=28), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_specialisms_id'), 'specialisms', ['id'], unique=False)
    op.add_column('candidate', sa.Column('specialism', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'candidate', 'specialisms', ['specialism'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'candidate', type_='foreignkey')
    op.drop_column('candidate', 'specialism')
    op.drop_index(op.f('ix_specialisms_id'), table_name='specialisms')
    op.drop_table('specialisms')
    # ### end Alembic commands ###
