"""departments and AM tables

Revision ID: 4cbba8332b54
Revises: 5dfa9c5d2177
Create Date: 2018-01-28 22:36:01.220597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cbba8332b54'
down_revision = '5dfa9c5d2177'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_department_name'), 'department', ['name'], unique=True)
    op.create_table('activity_manager',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('department', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['department'], ['department.id'], ),
    sa.ForeignKeyConstraint(['id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('first_name', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('last_name', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('type', sa.String(length=32), nullable=True))
    op.create_index(op.f('ix_user_first_name'), 'user', ['first_name'], unique=False)
    op.create_index(op.f('ix_user_last_name'), 'user', ['last_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_last_name'), table_name='user')
    op.drop_index(op.f('ix_user_first_name'), table_name='user')
    op.drop_column('user', 'type')
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'first_name')
    op.drop_table('activity_manager')
    op.drop_index(op.f('ix_department_name'), table_name='department')
    op.drop_table('department')
    # ### end Alembic commands ###
