"""changed region to region id on Role

Revision ID: 52e3aab34bbc
Revises: 71e3eaeaaac7
Create Date: 2018-03-21 21:33:04.734849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52e3aab34bbc'
down_revision = '71e3eaeaaac7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('roles_organisation_fkey', 'roles', type_='foreignkey')
    op.drop_constraint('roles_region_fkey', 'roles', type_='foreignkey')
    op.alter_column(table_name='roles', column_name='organisation', new_column_name='organisation_id')
    op.alter_column(table_name='roles', column_name='region', new_column_name='region_id')
    op.create_foreign_key('roles_organisation_id_fkey', 'roles', 'regions', ['region_id'], ['id'])
    op.create_foreign_key('roles_region_id_fkey', 'roles', 'organisation', ['organisation_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('roles_organisation_id_fkey', 'roles', type_='foreignkey')
    op.drop_constraint('roles_region_id_fkey', 'roles', type_='foreignkey')
    op.alter_column(table_name='roles', column_name='organisation_id', new_column_name='organisation')
    op.alter_column(table_name='roles', column_name='region_id', new_column_name='region')
    op.create_foreign_key('roles_region_fkey', 'roles', 'regions', ['region'], ['id'])
    op.create_foreign_key('roles_organisation_fkey', 'roles', 'organisation', ['organisation'], ['id'])
    # ### end Alembic commands ###
