"""added relocation column

Revision ID: 69346d6e05ed
Revises: 43797f6fee6d
Create Date: 2018-03-17 16:15:10.308511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69346d6e05ed'
down_revision = '43797f6fee6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('able_to_relocate', sa.Boolean()))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'able_to_relocate')
    # ### end Alembic commands ###
