"""changed specialism to specialism_id on Roles

Revision ID: 71e3eaeaaac7
Revises: 0cae55427427
Create Date: 2018-03-21 20:10:22.586764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71e3eaeaaac7'
down_revision = '0cae55427427'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('specialism_id', sa.Integer(), nullable=True))
    op.drop_constraint('roles_specialism_fkey', 'roles', type_='foreignkey')
    op.create_foreign_key(None, 'roles', 'specialisms', ['specialism_id'], ['id'])
    op.drop_column('roles', 'specialism')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('specialism', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'roles', type_='foreignkey')
    op.create_foreign_key('roles_specialism_fkey', 'roles', 'specialisms', ['specialism'], ['id'])
    op.drop_column('roles', 'specialism_id')
    # ### end Alembic commands ###
