"""made user users

Revision ID: 728292a59a2f
Revises: 56b18bf4ca67
Create Date: 2018-02-02 02:43:19.920462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '728292a59a2f'
down_revision = '56b18bf4ca67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('user', 'users')
    op.execute('ALTER SEQUENCE user_id_seq RENAME TO users_id_seq')
    op.execute('ALTER INDEX user_pkey RENAME TO users_pkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'candidate', type_='foreignkey')
    op.create_foreign_key('candidate_id_fkey', 'candidate', 'user', ['id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'activity_manager', type_='foreignkey')
    op.create_foreign_key('activity_manager_id_fkey', 'activity_manager', 'user', ['id'], ['id'], ondelete='CASCADE')
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('password_hash', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(length=24), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='user_pkey')
    )
    op.drop_index(op.f('ix_users_last_name'), table_name='users')
    op.drop_index(op.f('ix_users_first_name'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
