"""added basic CL and SL models

Revision ID: 783f7bedee53
Revises: f69ca39b9ffb
Create Date: 2018-02-07 23:40:59.438066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '783f7bedee53'
down_revision = 'f69ca39b9ffb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cohort_leader',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scheme_leader',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scheme_leader')
    op.drop_table('cohort_leader')
    # ### end Alembic commands ###
