"""changed match_score to total on Match

Revision ID: 78dc5aa5138f
Revises: 855f608eec2f
Create Date: 2018-03-22 16:34:26.529258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78dc5aa5138f'
down_revision = '855f608eec2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('total', sa.Integer(), nullable=True))
    op.drop_column('matches', 'match_score')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('match_score', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('matches', 'total')
    # ### end Alembic commands ###
