"""changed location to json type on preferences

Revision ID: 855f608eec2f
Revises: d26e0eb20d54
Create Date: 2018-03-22 10:13:42.802212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '855f608eec2f'
down_revision = 'd26e0eb20d54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('preferences', sa.Column('locations', sa.JSON(), nullable=True))
    op.drop_column('preferences', 'location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('preferences', sa.Column('location', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.drop_column('preferences', 'locations')
    # ### end Alembic commands ###
