"""skills is JSON now

Revision ID: 8a278c9d3583
Revises: 4d6890efedc5
Create Date: 2018-03-15 16:25:50.243125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a278c9d3583'
down_revision = '4d6890efedc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('preferences', sa.Column('skills', sa.JSON(), nullable=True))
    op.drop_column('preferences', 'skill1')
    op.drop_column('preferences', 'skill2')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('preferences', sa.Column('skill2', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column('preferences', sa.Column('skill1', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.drop_column('preferences', 'skills')
    # ### end Alembic commands ###
