"""cascading delete on AM to users table

Revision ID: 9a22f7b21ac1
Revises: 4fd9f70f753d
Create Date: 2018-01-28 23:19:18.221246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a22f7b21ac1'
down_revision = '4fd9f70f753d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('activity_manager_id_fkey', 'activity_manager', type_='foreignkey')
    op.create_foreign_key(None, 'activity_manager', 'user', ['id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'activity_manager', type_='foreignkey')
    op.create_foreign_key('activity_manager_id_fkey', 'activity_manager', 'user', ['id'], ['id'])
    # ### end Alembic commands ###
