"""added foreign keys to user candidate model

Revision ID: b391b04254ce
Revises: b4483194713b
Create Date: 2018-02-08 11:07:49.052750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b391b04254ce'
down_revision = 'b4483194713b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('line_manager_id', sa.Integer(), nullable=True))
    op.add_column('candidates', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint('candidates_line_manager_fkey', 'candidates', type_='foreignkey')
    op.drop_constraint('candidates_id_fkey', 'candidates', type_='foreignkey')
    op.create_foreign_key(None, 'candidates', 'users', ['line_manager_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'candidates', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('candidates', 'id')
    op.drop_column('candidates', 'line_manager')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('line_manager', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('candidates', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'candidates', type_='foreignkey')
    op.drop_constraint(None, 'candidates', type_='foreignkey')
    op.create_foreign_key('candidates_id_fkey', 'candidates', 'users', ['id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('candidates_line_manager_fkey', 'candidates', 'cohort_leaders', ['line_manager'], ['id'], ondelete='CASCADE')
    op.drop_column('candidates', 'user_id')
    op.drop_column('candidates', 'line_manager_id')
    # ### end Alembic commands ###
