"""added line_manager column to allow for CL interface

Revision ID: b4483194713b
Revises: 45f3eeaea47f
Create Date: 2018-02-08 10:55:46.540402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4483194713b'
down_revision = '45f3eeaea47f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('line_manager', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'candidates', 'cohort_leaders', ['line_manager'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'candidates', type_='foreignkey')
    op.drop_column('candidates', 'line_manager')
    # ### end Alembic commands ###
