"""added Base to user table at beginning of class call

Revision ID: b7c20ef6715f
Revises: bb37279ca9ac
Create Date: 2018-02-02 02:03:21.932873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7c20ef6715f'
down_revision = 'bb37279ca9ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('candidate')
    op.drop_table('activity_manager')
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=64), nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=64), nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), nullable=True),
    sa.Column('password_hash', sa.VARCHAR(length=128), nullable=True),
    sa.Column('type', sa.VARCHAR(length=16), nullable=False),
    sa.CheckConstraint("type IN ('candidate', 'activity manager', 'cohort leader')"),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activity_manager',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('organisation', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organisation'], ['organisation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('candidate',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('staff_number', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('staff_number')
    )
    # ### end Alembic commands ###
