"""new names

Revision ID: b8c18b09d237
Revises: 4a357332e312
Create Date: 2018-02-08 01:13:23.143207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8c18b09d237'
down_revision = '4a357332e312'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_managers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organisation', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organisation'], ['organisation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('staff_number', sa.Integer(), nullable=True),
    sa.Column('specialism', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['specialism'], ['specialisms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('staff_number')
    )
    op.create_table('scheme_leaders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('specialism', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['specialism'], ['specialisms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('candidate')
    op.drop_table('activity_manager')
    op.drop_table('scheme_leader')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheme_leader',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id'], ['users.id'], name='scheme_leader_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='scheme_leader_pkey')
    )
    op.create_table('activity_manager',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('organisation', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id'], ['users.id'], name='activity_manager_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organisation'], ['organisation.id'], name='activity_manager_organisation_fkey'),
    sa.PrimaryKeyConstraint('id', name='activity_manager_pkey')
    )
    op.create_table('candidate',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('staff_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('specialism', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id'], ['users.id'], name='candidate_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['specialism'], ['specialisms.id'], name='candidate_specialism_fkey'),
    sa.PrimaryKeyConstraint('id', name='candidate_pkey'),
    sa.UniqueConstraint('staff_number', name='candidate_staff_number_key')
    )
    op.drop_table('scheme_leaders')
    op.drop_table('candidates')
    op.drop_table('activity_managers')
    # ### end Alembic commands ###
