"""added id column on Candidate for joined inheritance

Revision ID: cb037c56c8d5
Revises: 69346d6e05ed
Create Date: 2018-03-17 16:25:32.729997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb037c56c8d5'
down_revision = '69346d6e05ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('staff_number', sa.Integer(), nullable=True),
    sa.Column('line_manager_id', sa.Integer(), nullable=True),
    sa.Column('able_to_relocate', sa.Boolean(), nullable=True),
    sa.Column('specialism', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['line_manager_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['specialism'], ['specialisms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('staff_number')
    )
    op.drop_constraint('users_staff_number_key', 'users', type_='unique')
    op.drop_constraint('users_line_manager_id_fkey', 'users', type_='foreignkey')
    op.drop_column('users', 'line_manager_id')
    op.drop_column('users', 'able_to_relocate')
    op.drop_column('users', 'staff_number')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('staff_number', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('able_to_relocate', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('line_manager_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('users_line_manager_id_fkey', 'users', 'users', ['line_manager_id'], ['id'])
    op.create_unique_constraint('users_staff_number_key', 'users', ['staff_number'])
    op.drop_table('candidates')
    # ### end Alembic commands ###
