"""added private office column

Revision ID: f69ca39b9ffb
Revises: ff792b4cb639
Create Date: 2018-02-07 22:29:58.298436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f69ca39b9ffb'
down_revision = 'ff792b4cb639'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('preferences', sa.Column('want_private_office', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('preferences', 'want_private_office')
    # ### end Alembic commands ###
