"""changed department column to organisation on preferences table

Revision ID: fa6852869418
Revises: b920c88043c2
Create Date: 2018-03-17 08:00:07.863544

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fa6852869418'
down_revision = 'b920c88043c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('preferences', sa.Column('organisation', sa.JSON(), nullable=True))
    op.drop_column('preferences', 'department')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('preferences', sa.Column('department', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('preferences', 'organisation')
    # ### end Alembic commands ###
