"""added completed_date column to preferences model

Revision ID: ff792b4cb639
Revises: 7703c8f6e318
Create Date: 2018-02-07 21:29:21.650456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff792b4cb639'
down_revision = '7703c8f6e318'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('preferences', sa.Column('completed_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('preferences', 'completed_date')
    # ### end Alembic commands ###
